import requests
import re
from bs4 import BeautifulSoup
import json

print("#####################################")
print("############ 한국 데이터 #############")
print("######## koreaRegionalData.js #########")

html = requests.get("http://ncov.mohw.go.kr/bdBoardList_Real.do?brdId=1&brdGubun=13&ncvContSeq=&contSeq=&board_id=&gubun=").text
# print(html)

soup = BeautifulSoup(html, 'html.parser')
업데이트날짜 = soup.select('.timetable > .info > span')[0].text
# print(f'업데이트날짜 : {업데이트날짜}')

# datas = soup.select('#maplayout > button')
datas = soup.select('.maplist > div')
# print(datas)
# print(datas[0])
# datas = datas[1:]

시도별확진자 = []

for d in datas:
    지역이름 = d.find_all('h4', class_='cityname')[0].text
    확진자수 = int(d.find_all('span', class_='num')[0].text[:-1].replace(',', ''))
    격리해제수 = int(d.find_all('span', class_='num')[2].text[:-1].replace(',', ''))
    사망자수 = int(d.find_all('span', class_='num')[1].text[:-1].replace(',', ''))
    십만명당발생율 = float(d.find_all('span', class_='num')[3].text[:-1])
    지역별확진자비율 = d.find_all('p', class_='citytit')

    # print(f'지역이름 : {지역이름}')
    # print(f'확진자수 : {확진자수}')
    # print(f'격리해제수 : {격리해제수}')
    # print(f'사망자수 : {사망자수}')
    # print(f'십만명당발생율 : {십만명당발생율}')

    for i in 지역별확진자비율:
        지역별확진자비율 = i.text[:4].replace('%', '')
        # print(f'지역별확진자비율 : {지역별확진자비율}')


    시도별확진자.append({
        '지역이름' : 지역이름,
        '확진자수' : 확진자수,
        '격리해제수' : 격리해제수,
        '사망자수' : 사망자수,
        '십만명당발생율' : 십만명당발생율,
        '지역별확진자비율' : 지역별확진자비율,
    })

# 삭제된 데이터 확인
# print(f'삭제된 데이터 : {시도별확진자[0]}')
시도별확진자.append({'업데이트날짜': 업데이트날짜})

with open("./data/koreaRegionalData.js", "w", encoding='UTF-8-sig') as json_file:
    json.dump(시도별확진자, json_file, ensure_ascii=False, indent=4)

data = ''
with open("./data/koreaRegionalData.js", "r", encoding='UTF-8-sig') as f:
    while True:
        line = f.readline()
        if not line: break
        data += line
data = '//Auto-generated by crawlKoreaRegionalData.py\nvar koreaRegionalData = ' + data + ';'

with open("./data/koreaRegionalData.js", "w", encoding='UTF-8-sig') as f_write:
    f_write.write(data)
print("############### 완료!! ###############")
print("#####################################")
