import requests
import re
from bs4 import BeautifulSoup
import json
from previousWorldData import previous_data

print("#####################################")
print("############ 세계 데이터 #############")
print("######## worldData.js #########")

html = requests.get("https://www.worldometers.info/coronavirus/").text
# print(html) 작동확인 1
soup = BeautifulSoup(html, 'html.parser')
datas = soup.select('#main_table_countries > tbody > tr')
# print(datas) 작동확인 2

world_confirmed = []

for d in datas:
    country = d.find_all('td')[0].text
    if country.strip() == 'S. Korea':
        continue
    confirmed = d.find_all('td')[1].text
    deaths = d.find_all('td')[3].text
    recovered = d.find_all('td')[5].text
    # print(f'국가이름 : {국가이름}')
    # print(f'확진자 : {확진자}')
    # print(f'사망자 : {사망자}')
    # print(f'완치자 : {완치자}')

    country_kr = ''
    country_cn = ''

    for value in previous_data:
        if value['Name_en'] == country.strip():
            country_kr = value['Name']
            name_ch = value['Name_ch']

    #지도 SVG 이름 동기화(아래 USA는 크롤링된 영어이름)
    if country.strip() == 'USA':
        #여기에 SVG파일에 있는 국가명으로 변경
        country = 'United States'

    #잘못된 영어이름 수정
    if country.strip() == 'USA':
        #여기에 SVG파일에 있는 국가명으로 변경
        country = 'United States'

    if country.strip() == 'Total:':
      print("Skipping total")
      continue

    #한국어 이름이 필드에 없을 경우 영어이름 삽입
    if country_kr == '':
        country_kr = country.strip()

    world_confirmed.append({
        'Name' : country_kr,
        'Name_ch' : country_cn,
        'Name_en' : country.strip(),
        '확진자수' : int(0 if confirmed.strip().replace(',', '') == "" else confirmed.strip().replace(',', '')),
        '사망자수' : int(0 if deaths.strip().replace(',', '') == "" else deaths.strip().replace(',', '')),
        '완치자수' : int(0 if recovered.strip().replace(',', '') == "" else recovered.strip().replace(',', '')),
    })

with open("./data/worldData.js", "w", encoding='UTF-8-sig') as json_file:
    json.dump(world_confirmed, json_file, ensure_ascii=False, indent=4)
    # file.write(json.dumps(dict, ensure_ascii=False))

data = ''
with open("./data/worldData.js", "r", encoding='UTF-8-sig') as f:
    while True:
        line = f.readline()
        if not line: break
        data += line
data = '//Auto-generated by crawlWorldData.py\nvar marker = ' + data + ';'

with open("./data/worldData.js", "w", encoding='UTF-8-sig') as f_write:
    f_write.write(data)

print("############### 완료!! ###############")
print("#####################################")
