import json
import re

import requests

from bs4 import BeautifulSoup


def get_data(url):
    ageDeathsPer = []
    html = requests.get(url).text
    soup = BeautifulSoup(html, 'html.parser')
    data = soup.select('.num > tbody > tr')

    for datum in data[4:]:
        temp = [i.text.replace('\xa0', '') for i in datum]
        ageDeathsPer.append({
            '구분': temp[0],
            '확진자(%)': temp[1],
            '사망자(%)': temp[2],
            '치명율': temp[3]
        })

    return ageDeathsPer


def run():
    ageDeathsPer = get_data("http://ncov.mohw.go.kr/bdBoardList_Real.do?brdId=1&brdGubun=11&ncvContSeq=&contSeq=&board_id=&gubun=")

    with open("./data/koreaAgeDeathsPerData.js", "w", encoding='UTF-8-sig') as json_file:
        json.dump(ageDeathsPer, json_file, ensure_ascii=False, indent=4)

    data = ''
    with open("./data/koreaAgeDeathsPerData.js", "r", encoding='UTF-8-sig') as f:
        while True:
            line = f.readline()
            if not line:
                break
            data += line
    data = '//Auto-generated by crawlKoreaAgeDeathsPerData.py\nvar ageDeathsPer = ' + data + ';'

    with open("./data/koreaAgeDeathsPerData.js", "w", encoding='UTF-8-sig') as f_write:
        f_write.write(data)


if __name__ == '__main__':
    print("#####################################")
    print("############ 한국 나이별 치명율 데이터 #############")
    print("######## koreaAgeStatusData.js #########")
    run()
    print("############### 완료!! ###############")
    print("#####################################")
