import requests
import re
from bs4 import BeautifulSoup
import json

print("#####################################")
print("############ 한국 데이터 #############")
print("######## koreaRegionalData.js #########")

html = requests.get("http://ncov.mohw.go.kr/bdBoardList_Real.do?brdId=1&brdGubun=13&ncvContSeq=&contSeq=&board_id=&gubun=").text
# print(html)

soup = BeautifulSoup(html, 'html.parser')
updated = soup.select('.timetable > .info > span')[0].text     # 업데이트날짜

# datas = soup.select('#maplayout > button')
datas = soup.select('.rpsa_detail > div > div')
# print(datas)
# print(datas[0])
# datas = datas[1:]

confirmed_region = []   # 시도별확진자
count = 0

for d in datas:
    region = d.find_all('h4', class_='cityname')[0].text      # 지역이름
    confirmed = int(d.find_all('span', class_='num')[0].text.replace(',', ''))    # 확진자수
    recovered = int(d.find_all('span', class_='num')[2].text.replace(',', ''))   # 격리해제수
    deaths = int(d.find_all('span', class_='num')[1].text.replace(',', ''))  # 사망자수
    confirmed_rate = float(d.find_all('span', class_='num')[3].text.replace('-', '0'))   # 십만명당발생율
    confirmed_region_rate = ''
    if count != 0:
        슬라이싱 = d.find_all('p', class_='citytit')[0].text
        confirmed_region_rate = float(슬라이싱[:슬라이싱.find('%')])    # 지역별확진자비율

    confirmed_region.append({
        '지역이름' : region,
        '확진자수' : confirmed,
        '격리해제수' : recovered,
        '사망자수' : deaths,
        '십만명당발생율' : confirmed_rate,
        '지역별확진자비율' : confirmed_region_rate,
    })
    print(count)
    count += 1

# 삭제된 데이터 확인
# print(f'삭제된 데이터 : {시도별확진자[0]}')
confirmed_region.append({'업데이트날짜': updated})

print(confirmed_region)

with open("./data/koreaRegionalData.js", "w", encoding='UTF-8-sig') as json_file:
    json.dump(confirmed_region, json_file, ensure_ascii=False, indent=4)

data = ''
with open("./data/koreaRegionalData.js", "r", encoding='UTF-8-sig') as f:
    while True:
        line = f.readline()
        if not line: break
        data += line
data = '//Auto-generated by crawlKoreaRegionalData.py\nvar koreaRegionalData = ' + data + ';'

with open("./data/koreaRegionalData.js", "w", encoding='UTF-8-sig') as f_write:
    f_write.write(data)
print("############### 완료!! ###############")
print("#####################################")
